// supabase/functions/delete-account/index.ts
//
// Permanent self-service account deletion (readiness #8). verify_jwt
// guarantees a valid project JWT; we then resolve the CALLER from that JWT
// and delete exactly that user — no id parameter is accepted, so nobody can
// delete anyone but themselves. profiles has ON DELETE CASCADE from
// auth.users, and user_push_tokens cascades from profiles, so the chain
// cleans up. Field reports are intentionally kept (public-health record),
// but are detached from the deleted identity by the FK behavior of their
// reporter columns.
//
// SOURCE PROVENANCE (SEC-16): this file was recovered from the DEPLOYED
// function on 2026-08-02 and committed unchanged. Until then it existed only
// on Supabase's servers — v1, deployed once, with no copy in the repository.
// A function that can permanently delete a user account was therefore not
// reviewable, not diffable, and not restorable if the deployment were lost.
// Do not edit this file without redeploying, and do not redeploy without
// editing this file; the two must not drift again.

import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

Deno.serve(async (req: Request): Promise<Response> => {
  if (req.method === "OPTIONS") {
    return new Response(null, {
      headers: {
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Headers": "authorization, content-type, apikey, x-client-info",
        "Access-Control-Allow-Methods": "POST, OPTIONS",
      },
    });
  }
  if (req.method !== "POST") {
    return new Response(JSON.stringify({ error: "Method not allowed" }), { status: 405 });
  }

  try {
    const body = await req.json().catch(() => ({}));
    if (body?.confirm !== "DELETE") {
      return new Response(
        JSON.stringify({ error: 'Confirmation required: send {"confirm":"DELETE"}' }),
        { status: 400, headers: { "Content-Type": "application/json" } }
      );
    }

    const authHeader = req.headers.get("Authorization") ?? "";
    const jwt = authHeader.replace(/^Bearer\s+/i, "");
    const admin = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
    );

    const { data: userData, error: userErr } = await admin.auth.getUser(jwt);
    if (userErr || !userData?.user) {
      return new Response(JSON.stringify({ error: "Could not identify the signed-in user" }), {
        status: 401, headers: { "Content-Type": "application/json" },
      });
    }
    const uid = userData.user.id;

    // Guard: the last active super_admin cannot delete themselves — the
    // system would become unadministrable.
    const { data: me } = await admin.from("profiles").select("role").eq("id", uid).single();
    if (me?.role === "super_admin") {
      const { count } = await admin
        .from("profiles")
        .select("id", { count: "exact", head: true })
        .eq("role", "super_admin")
        .eq("is_active", true);
      if ((count ?? 0) <= 1) {
        return new Response(
          JSON.stringify({ error: "You are the only active super admin — transfer the role before deleting this account." }),
          { status: 409, headers: { "Content-Type": "application/json" } }
        );
      }
    }

    const { error: delErr } = await admin.auth.admin.deleteUser(uid);
    if (delErr) {
      console.error("deleteUser failed:", delErr.message);
      return new Response(JSON.stringify({ error: "Deletion failed — try again or contact support" }), {
        status: 500, headers: { "Content-Type": "application/json" },
      });
    }

    console.log(`account deleted: ${uid}`);
    return new Response(JSON.stringify({ success: true }), {
      status: 200, headers: { "Content-Type": "application/json" },
    });
  } catch (err) {
    console.error("delete-account error:", err);
    return new Response(JSON.stringify({ error: String(err) }), {
      status: 500, headers: { "Content-Type": "application/json" },
    });
  }
});
